[package]

# Semantic Versioning is used: https://semver.org/
version = "0.1.0"

# Description
title = "Extension Template"  # TODO
description="Extension Template for Orbit"  #TODO
repository = "https://github.com/isaac-orbit/orbit.ext_template.git"  # TODO, add your_repository_url
keywords = ["extension", "template", "orbit"]  # TODO
category = "orbit"
readme  = "README.md"

[dependencies]
"omni.kit.uiapp" = {}
# "omni.isaac.orbit" = {}  # TODO, add additional dependencies if required

[[python.module]]
name = "orbit.ext_template"  # TODO, replace <ext_template> with <your_extension_name>